sudo: required
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - 8

env:
  global:
    - secure: "SP1gDLIydLI7OLjLSi0162OGr19iKJfAyoRYUWj52pMrImT/Hvp4EJaxs1+PCB9LEL29AueHX7Kt8BIYJ86/rAKzbV+hITS1kYXC3MnRZJ0gxhZ1eobeZuAAIh9T6fPHrkABv2O+6I2KZ7sJBBC8oeXoVgKGc2UFW6LLXQ0A+yygWhm2v/5WozEHpA5ftEcHQXxilFyUsa7KidEp7J6D0mTpMuge+oxNuRODODZt0HJuC8NWpfYKOv7U9q389/41Mxn5+Hqdzjw5XqIqLRYfEgvZRaN8NGbQWXHrrbWJMyDkwfKgj+pPhFA6j3JWwo7BWfhJX4vv7zc9r31hdIOrlnNSYzjdRR/5q9YwI1hPQG750gYEUIRyZ5fVlw/YVeKUoeZfG84gioKd/rBJ/m9zbURs8srDQtt7YOyG4c0wrGWWfvPVUunen3lGrk9qJvAHngtOeTimM+eqycsvaACqEYLduwP+DjoXh5rNTyaf8SqxcUNYe3f0ms1EoyulB8TZfxGBvTWNYatnzGkdIiODQgAT4sM7osFdRBQWUe2OiCJirhmE+Dycv3sQnU7WRmv9NIJpL4f2bRrS3IOGw1lj+1ogEStfCMD47YJ04UXdi9DPMa/opVg8sIUYm0Q5UT3fUeBuRGIrNpF3rRMrtjWCbvHe6vP3drlABZxy8LuSOqY="

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install
  - npm install -g angular-cli-ghpages

script:
  - npm run test
  - npm run e2e
  - npm run build
  - npm run build-ghpages

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ] ; then angular-cli-ghpages --dir="dist-ghpages" --repo="https://${GH_TOKEN}@github.com/unm-idi/splendid-view.git" --name="Sr. Travis" --email="hi@travis.org"; fi

before_deploy:
  - cd dist

deploy:
  provider: npm
  email: unm-idi+npm@gmail.com
  api_key: 
    secure: "fzoTXcqcaHlU+2j++scR0NhuZaAefzrEF+WJQPgtvjVsaEuhoWZ2t6nszLmWcWpbC+M/+/VaMOqFG/66PIeew8GzdMMT9yCKrUy3TMJ38gCEDa6+9FuP1Wc0rb5JIQ8WcM7dicgGVv9QVZ3mS78g1eBm4vI7seD+DtQdUFG17+6i1qU9P+MpoF7z3FX1m1UZN7F+DEwJAE5VIgZrY7885bV7yVap9EPdKbu0UsRW0cizapqPTi4azfz2BkVMCSieDakopxxRVYCwDYqMuu91620vu9LZvFyKW15aAeR802ICGDfRBfjGMRbrsef5vcTIA4HyMiixMhUs01y9CXVIjw8EX3vJ+2KiwW6O5JMyqbOtH0h5T69mORJvXSH3jZUSMUUIqc8KFd+OyHKXUTMyUk6gp+riljezEzssG5Ao6ouCHcVRCv9rVqniBCYY9XQVI04bLaxPBtv1SPWYUbEHfa3izU4GDTIVnrbziDhoA4oPAZV5B40ogsvMCYvp/af+8GXWbtAd7T4vyfiMZvnsDU3cLR4MBaUPhLBuw9sPxxgHBg66d9Jby+O/wsVHuabO0D2aQnlMJIFVHevm9eVIat45P3CAOlffglbr9w62LEp3XF18BPFxVok+eEeKNKAmitTugm0U7GbNXn8WpyYaczv6g7QshdpzwkXEfp9U3z0="
  on:
    branch: master
  skip_cleanup: true
